### ISSUE TITLE
Breaking website with release from 23/03/2023

### ISSUE THREAD

**Issue by harryqover** [cookieyeshq/cookieyes-gtm-template#4]
When adding the new template released the 23rd of March, it breaks my website with this error:
<img width="957" alt="Capture d’écran 2023-04-05 à 13 16 24" src="https://user-images.githubusercontent.com/97823153/230065050-99108ab8-d1bc-44f2-a3de-84c321fd5cd6.png">

Uncaught RangeError: Maximum call stack size exceeded
    at document.createElement (script.js:1:92966)
    at document.createElement (script.js:1:93050)
    at document.createElement (script.js:1:93050)
    at document.createElement (script.js:1:93050)
    at document.createElement (script.js:1:93050)
    at document.createElement (script.js:1:93050)
    at document.createElement (script.js:1:93050)
    at document.createElement (script.js:1:93050)
    at document.createElement (script.js:1:93050)
    at document.createElement (script.js:1:93050)
2script.js:1 Uncaught RangeError: Maximum call stack size exceeded

**Comment by cookieyeshq** [comment]
Hello @harryqover ,

Apologies for the slight delay in responding. We understand your concern and we would be more than happy to help you with the same.
Since this issue is specific to your case it would be great if you can raise a ticket here: https://www.cookieyes.com/support/ so that our support team can help you with the same on priority.
